version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - server-network

  app:
    image: ing3616062/emgapp-0.0.36-snapshot
    container_name: app-container
    ports:
      - 8080:8080
    env_file:
      - "./.env"
    environment:
      - TZ=Asis/Seoul
    depends_on:
      - db
    links:
      - db
    networks:
      - server-network
    restart: always

networks:
  server-network:

volumes:
  mysql-data:
