spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/application?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&&allowPublicKeyRetrieval=true
    username: root
    password: ab3616062

  jpa:
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

security.jwt.token:
  secret-key: tteesstt
  access-key-expire-length: 864000
  refresh-key-expire-length: 1728000

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: dlcksgml
    nonce: ${OAUTH_APPLE_NONCE}