spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  servlet:
    multipart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

security.jwt.token:
  secret-key: ${JWT_SECRET_KEY}
  access-key-expire-length: ${JWT_ACCESS_TOKEN_EXPIRE}
  refresh-key-expire-length: ${JWT_REFRESH_TOKEN_EXPIRE}

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: ${APPLE_CLIENT_ID}
    nonce: ${APPLE_NONCE}

server:
  ssl:
    enabled: true
    key-store-password: ${SSL_PASSWORD}
    key-store: ${SSL_KEY_STORE}
    key-store-type: ${SSL_STORE_TYPE}

fcm:
  path: ${FCM_CLASS_PATH}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error