version : "3.3"
services:
  database:
    image: mysql:8.0.30
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: ab3616062
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: test
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/application?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ab3616062
    networks:
      - springboot-mysql-net
networks:
  springboot-mysql-net:
    driver: bridge
