name: Java CD with Gradle

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app-jar
          path: .

      - name: Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build -x test

      # DockerHub Login
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker 이미지 Build
      - name: docker image build
        run: docker buildx build --platform linux/amd64 -t ing3616062/emgapp-0.0.1-snapshot .

      # Docker Hub push
      - name: docker Hub push
        run: docker push ing3616062/emgapp-0.0.1-snapshot
