name: Java CD with Gradle

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: git pull
        run: |
          sudo docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          git pull

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            sudo docker stop ${{ secrets.DOCKER_APP_CONTAINER }}
            sudo docker rm ${{ secrets.DOCKER_APP_CONTAINER }}
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/emgapp-0.0.1-snapshot
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/emgapp-0.0.1-snapshot
            sudo docker-compose up -d


